name: flutter_ebook_app
description: Flutter EBook app with getx State Management
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  cached_network_image: ^3.2.3
  dio: ^5.2.0
  flutter_spinkit: ^5.2.0
  google_fonts: ^4.0.4
  path: ^1.8.3
  path_provider: ^2.0.15
  permission_handler: ^10.2.1
  sembast: ^3.4.6+1
  share_plus: ^7.0.2
  shared_preferences: ^2.1.1
  xml2json: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
